import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20

[font]
size = 14.0

[font.bold]
family = "SFMono Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "SFMono Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "SFMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "SFMono Nerd Font Mono"
style = "Medium"
